apiVersion: v1
kind: Service
metadata:
  name: flask-service-dev
  labels:
    service: flaskservicedev
spec:
  selector:
    app: esdeployment
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000