apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment 
  labels:
    name: esdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esdeployment
  template:
    metadata:
      labels:
        app: esdeployment
    spec:
      containers:
      - name: esdeployment
        image: thiernodocker/es-lask:v2
      restartPolicy: Always
