apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    service: flask-service
spec:
  selector:
    app: es-deployment
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
